services:
  nginx:
    container_name: nginx
    build: 
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception-network
    volumes:
      - wp-volume:/var/www/
    restart: always
  
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    networks:
      - inception-network
    expose:
      - "3306"
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DOMAIN_NAME: ${DOMAIN_NAME}
        WPADUSER: ${WPADUSER}
        WPUSER1: ${WPUSER1}
        WPADPASS: ${WPADPASS}
        WPUSER1PASS: ${WPUSER1PASS}
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wp-volume:/var/www/
    networks:
      - inception-network
    env_file:
      - .env
    expose:
      - "9000"


volumes:
  wp-volume:
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '~/data/wordpress'

  db-volume:
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '~/data/mariadb'

networks:
    inception-network:
      driver: bridge