FLUSH PRIVILEGES;

DELETE FROM mysql.user WHERE user='';
DROP DATABASE IF EXISTS test;
DELETE FROM mysql.db WHERE db='test';

DELETE FROM mysql.user WHERE user='root' AND host NOT IN ('localhost', '127.0.0.1', '::1');
SET PASSWORD FOR 'root'@'localhost' = PASSWORD('$DB_ROOT');

CREATE DATABASE IF NOT EXISTS `$DB_NAME`;
CREATE USER IF NOT EXISTS '$DB_USER'@'%' IDENTIFIED by '$DB_PASS';
GRANT ALL PRIVILEGES ON `$DB_NAME`.* TO '$DB_USER'@'%';

FLUSH PRIVILEGES;

/* 
    1. SHOW DATABASES;
    2. SELECT user FROM mysql.user;
 */